# -*- coding: utf-8 -*-
"""
/***************************************************************************
 eziudp_plugin2
                                 A QGIS plugin
 eziudp_plugin2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-06
        copyright            : (C) 2025 by Łukasz Świątek
        email                : lukasz.swiatek1996@gmaill.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load eziudp_plugin2 class from file eziudp_plugin2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .eziudp_plugin2 import eziudp_plugin2
    return eziudp_plugin2(iface)
