# -*- coding: utf-8 -*-
"""
/***************************************************************************
 eziudp_plugin2
                                 A QGIS plugin
 eziudp_plugin2
 Generated by Plugin Builder
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QUrl
from qgis.PyQt.QtGui import QIcon, QDesktopServices, QColor
from qgis.PyQt import QtWidgets
from qgis.core import (
    QgsRasterLayer, QgsVectorLayer, QgsProject, QgsFeatureRequest, QgsGeometry,
    QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsRectangle, QgsFeature
)
from qgis.PyQt.QtWidgets import QAction, QDialog, QVBoxLayout, QListWidget, QListWidgetItem, QPushButton
from qgis.gui import QgsMapToolEmitPoint, QgsRubberBand
import os.path, re, requests

from .resources import *
from .eziudp_plugin2_dockwidget import EziudpPlugin2Dockwidget


# ===============================
# DIALOG WYBORU WARSTW
# ===============================
class LayerSelectionDialog(QDialog):
    def __init__(self, layers, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Wybierz warstwy do dodania")
        self.resize(400, 300)
        layout = QVBoxLayout(self)
        self.list_widget = QListWidget()
        for name, title in layers:
            item = QListWidgetItem(f"{title} ({name})")
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            item.setCheckState(Qt.Unchecked)
            self.list_widget.addItem(item)
        layout.addWidget(self.list_widget)
        self.btn_ok = QPushButton("Dodaj zaznaczone")
        self.btn_ok.clicked.connect(self.accept)
        layout.addWidget(self.btn_ok)

    def get_selected(self):
        selected = []
        for i in range(self.list_widget.count()):
            item = self.list_widget.item(i)
            if item.checkState() == Qt.Checked:
                selected.append(item.text())
        return selected


# ===============================
# NARZĘDZIE KLIKNIĘCIA NA MAPIE
# ===============================
class PointTool(QgsMapToolEmitPoint):
    def __init__(self, iface, callback):
        super().__init__(iface.mapCanvas())
        self.iface = iface
        self.callback = callback

    def canvasReleaseEvent(self, event):
        point = self.toMapCoordinates(event.pos())
        self.callback(point)
        self.iface.mapCanvas().unsetMapTool(self)


# ===============================
# FUNKCJE OBSŁUGI GETCAPABILITIES
# ===============================
def fetch_capabilities(url: str):
    """Pobiera dokument GetCapabilities i zwraca listę nazw warstw oraz typ usługi."""
    try:
        if "SERVICE=WFS" in url.upper():
            service_type = "WFS"
        elif "SERVICE=WMS" in url.upper():
            service_type = "WMS"
        else:
            if "wfs" in url.lower():
                service_type = "WFS"
                url = url.split("?")[0]
                url += "?SERVICE=WFS&REQUEST=GetCapabilities"
            else:
                service_type = "WMS"
                url = url.split("?")[0]
                url += "?SERVICE=WMS&REQUEST=GetCapabilities"

        response = requests.get(url, timeout=10)
        response.raise_for_status()
        text = response.text

        names = re.findall(r"<Name.*?>(.*?)</Name>", text)
        titles = re.findall(r"<Title.*?>(.*?)</Title>", text)
        if len(titles) > len(names):
            titles = titles[-len(names):]

        layers = list(zip(names, titles))
        return layers, service_type
    except Exception as e:
        print("Błąd pobierania GetCapabilities:", e)
        return [], url


def add_layers_from_service(url: str, iface):
    layers, service_type = fetch_capabilities(url)
    if not layers:
        iface.messageBar().pushWarning("EZiUDP", f"Nie udało się pobrać listy warstw z\nURL:{service_type}")
        return

    dlg = LayerSelectionDialog(layers)
    if dlg.exec_():
        selected = dlg.get_selected()
        if not selected:
            iface.messageBar().pushInfo("EZiUDP", "Nie wybrano żadnych warstw.")
            return

        for layer_text in selected:
            m = re.search(r"\((.*?)\)$", layer_text)
            if not m:
                continue
            layer_name = m.group(1)

            if service_type == "WMS":
                clean_url = re.sub(r"[?&]request=GetCapabilities", "", url, flags=re.I)
                clean_url = re.sub(r"[?&]service=WMS", "", clean_url, flags=re.I)
                base_url = clean_url.split("?")[0]
                params = "?" + "&".join([p for p in clean_url.split("?")[1:] if p])
                if not params.endswith("&"):
                    params += "&"
                layer_url = f"url={base_url}{params}service=WMS&request=GetMap&layers={layer_name}&styles=&format=image/png&crs=EPSG:2180"
                # rlayer = QgsRasterLayer(layer_url, layer_name, "wms")
                # layer_url = f"{base_url}{params}&layers={layer_name}&styles=&format=image/png&crs=EPSG:2180"
                rlayer = QgsRasterLayer(layer_url, layer_name, "wms")
                if rlayer.isValid():
                    QgsProject.instance().addMapLayer(rlayer)
                else:
                    iface.messageBar().pushWarning("EZiUDP", f"Nie udało się dodać WMS: {layer_name}")


            elif service_type == "WFS":
                layer_url = f"{url}?service=WFS&version=2.0.0&request=GetFeature&typeName={layer_name}"
                vlayer = QgsVectorLayer(layer_url, layer_name, "WFS")
                if vlayer.isValid():
                    QgsProject.instance().addMapLayer(vlayer)
                else:
                    layer_url = f"{url}?service=WFS&version=1.1.0&request=GetFeature&typeName={layer_name}"
                    vlayer = QgsVectorLayer(layer_url, layer_name, "WFS")
                    if vlayer.isValid():
                        QgsProject.instance().addMapLayer(vlayer)
                    else:
                        iface.messageBar().pushWarning("EZiUDP", f"Nie udało się dodać WFS: {layer_name}")



class TerytSelectionDialog(QDialog):
    """Okno wyboru jednostki TERYT z podświetleniem na mapie."""
    def __init__(self, iface, layer, teryt_features):
        super().__init__()
        self.iface = iface
        self.layer = layer
        self.teryt_features = teryt_features
        self.setWindowTitle("Wybór jednostki TERYT")
        self.resize(300, 300)

        layout = QVBoxLayout()
        self.list_widget = QListWidget()
        for f in teryt_features:
            teryt = f["TERYT"]
            self.list_widget.addItem(str(teryt))
        layout.addWidget(self.list_widget)

        self.btn_ok = QPushButton("Wybierz")
        self.btn_ok.clicked.connect(self.on_accept)
        layout.addWidget(self.btn_ok)
        self.setLayout(layout)

        # RubberBand do podświetlenia
        self.rubber = QgsRubberBand(self.iface.mapCanvas())
        # self.rubber.setColor(Qt.yellow)
        self.rubber.setFillColor(QColor(255, 255, 0, 30))
        self.rubber.setColor(QColor(255, 255, 0, 180))
        self.rubber.setWidth(2)

        # Reakcja na zmianę wyboru
        self.list_widget.currentRowChanged.connect(self.highlight_feature)

    def highlight_feature(self, index):
        """Podświetla aktualnie zaznaczony obiekt."""
        self.rubber.reset()
        if index < 0 or index >= len(self.teryt_features):
            return
        feature = self.teryt_features[index]
        geom = feature.geometry()
        self.rubber.setToGeometry(geom, self.layer)
        self.iface.mapCanvas().zoomToFeatureIds(self.layer, [feature.id()])

    def get_selected_teryt(self):
        row = self.list_widget.currentRow()
        if row < 0:
            return None
        return str(self.teryt_features[row]["TERYT"])
    
    def on_accept(self):
        """Zatwierdzenie wyboru + wyczyszczenie zaznaczenia"""
        self.rubber.reset()      # ← usuwa zaznaczenie natychmiast
        self.accept()

    def closeEvent(self, event):
        self.rubber.reset()
        super().closeEvent(event)


# ===============================
# GŁÓWNA KLASA PLUGINU
# ===============================
class eziudp_plugin2:
    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = self.tr(u'&eziudp_plugin2')
        self.toolbar = self.iface.addToolBar(u'eziudp_plugin2')
        self.toolbar.setObjectName(u'eziudp_plugin2')
        self.pluginIsActive = False
        self.dockwidget = None
        # Wczytaj warstwę GeoJSON z TERYT (jeśli istnieje)
        self.layer_teryt = None
        geojson_path = os.path.join(self.plugin_dir, "gminy.geojson")
        if os.path.exists(geojson_path):
            self.layer_teryt = QgsVectorLayer(geojson_path, "TERYT_zasiegi", "ogr")

    def load_teryt_layer(self):
        rodzaj = self.dockwidget.comboBox.currentText()
        path = os.path.join(self.plugin_dir, f"{rodzaj}.geojson")
        self.layer_teryt = QgsVectorLayer(path, rodzaj, "ogr")
        if not self.layer_teryt.isValid():
            QtWidgets.QMessageBox.warning(None, "Błąd", f"Nie udało się wczytać warstwy {path}")


    def tr(self, message):
        return QCoreApplication.translate('eziudp_plugin2', message)

    def add_action(self, icon_path, text, callback, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        self.toolbar.addAction(action)
        self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/eziudp_plugin2/icon.png'
        self.add_action(icon_path, text=self.tr(u'EZiUDP'), callback=self.run, parent=self.iface.mainWindow())

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    # ===============================
    # OBSŁUGA KLIKNIĘCIA I TERYT
    # ===============================
    def activate_point_tool(self):
        if not self.layer_teryt:
            QtWidgets.QMessageBox.warning(None, "Brak warstwy", "Brak warstwy GeoJSON z zasięgami TERYT.")
            return
        
        self.iface.messageBar().pushMessage("EZiUDP", "Wskaż punkt na mapie, aby ustalić TERYT", duration=4)
        self.point_tool = PointTool(self.iface, self.point_selected)
        self.iface.mapCanvas().setMapTool(self.point_tool)

    def point_selected(self, point):
        print(f"Kliknięto: {point.x():.2f}, {point.y():.2f}")

        rodzaj = self.dockwidget.comboBox.currentText()
        # teryt = self.get_teryt_from_point(point, rodzaj)
        # self.dockwidget.lineEditTeryt.setText(teryt)

        self.load_teryt_layer()

        if not self.layer_teryt:
            QtWidgets.QMessageBox.warning(None, "Brak warstwy", "Nie wczytano warstwy TERYT.")
            return

        crs_src = self.iface.mapCanvas().mapSettings().destinationCrs()
        crs_dst = self.layer_teryt.crs()
        transform = QgsCoordinateTransform(crs_src, crs_dst, QgsProject.instance())
        point_layer_crs = transform.transform(point)
        # geom = QgsGeometry.fromPointXY(point_layer_crs)

        # for f in self.layer_teryt.getFeatures(QgsFeatureRequest().setFilterRect(geom.boundingBox())):
        #     if f.geometry().intersects(geom):
        #         teryt = f["TERYT"]
        #         self.dockwidget.terytInput.setText(str(teryt))
        #         self.iface.messageBar().pushMessage("EZiUDP", f"Znaleziono jednostkę: {teryt}", duration=4)
        #         self.search_eziudp()
        #         return

        # Znajdź wszystkie obiekty, które przecinają punkt
        rect = QgsRectangle(point_layer_crs.x() - 0.01, point_layer_crs.y() - 0.01,
                            point_layer_crs.x() + 0.01, point_layer_crs.y() + 0.01)
        
        teryt_list = []
        for feat in self.layer_teryt.getFeatures(QgsFeatureRequest().setFilterRect(rect)):
            geom = feat.geometry()
            if geom.contains(point_layer_crs):
                teryt = feat["TERYT"] if "TERYT" in feat.fields().names() else None
                if teryt:
                    teryt_list.append(teryt)

        # Reakcja w zależności od liczby trafień
        if not teryt_list:
            QtWidgets.QMessageBox.information(None, "EZiUDP", "Nie znaleziono jednostki dla wskazanego punktu.")
            return
        
        if len(teryt_list) == 1:
            selected_teryt = teryt_list[0]
        else:
            # selected_teryt, ok = QtWidgets.QInputDialog.getItem(
            #    None,
            #    "Wybór jednostki",
            #    "Znaleziono kilka jednostek w otoczeniu wybranego punktu.\nWybierz numer TERYT:",
            #    teryt_list,
            #    0,
            #    False
            # )

            # Pobierz pełne featury zamiast samych kodów
            features = []
            for feat in self.layer_teryt.getFeatures(QgsFeatureRequest().setFilterRect(rect)):
                geom = feat.geometry()
                if geom.contains(point_layer_crs):
                    features.append(feat)

            dlg = TerytSelectionDialog(self.iface, self.layer_teryt, features)
            if dlg.exec_():
                selected_teryt = dlg.get_selected_teryt()
                if not selected_teryt:
                    return
                    if not ok:
                        return


        # Ustaw numer w interfejsie
        self.dockwidget.terytInput.setText(selected_teryt)
        self.iface.messageBar().pushMessage("EZiUDP", f"Wybrano TERYT: {selected_teryt}", duration=4)
        self.search_eziudp()


        # QtWidgets.QMessageBox.information(None, "Brak", "Nie znaleziono jednostki administracyjnej dla tego punktu.")

    # ===============================
    # WYSZUKIWANIE EZiUDP
    # ===============================
    def search_eziudp(self):
        teryt = self.dockwidget.terytInput.text().strip()
        jedn = self.dockwidget.comboBox.currentText()

        if not teryt:
            if jedn != "jednostki centralne":
                QtWidgets.QMessageBox.warning(None, "Błąd", "Podaj numer TERYT.")
                return
        
        if jedn == "powiaty":
            teryt = teryt[:4]
        elif jedn == "wojewodztwa":
            teryt = teryt[:2]
        elif jedn == "gminy":
            teryt = teryt[:6]
        elif jedn == "jednostki centralne":
            jedn = "centralne"
            teryt = "PL"

        url = f"https://integracja.gugik.gov.pl/eziudp/index.php?teryt={teryt}&rodzaj={jedn}&nazwa=&zbior=&temat=&usluga=&adres="
        try:
            html = requests.get(url, timeout=10).text
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Błąd", f"Nie udało się pobrać danych:\n{e}")
            return

        rows = re.findall(r"<tr.*?>(.*?)</tr>", html, re.S | re.I)
        if not rows:
            QtWidgets.QMessageBox.warning(None, "Brak danych", "Nie znaleziono żadnych zbiorów dla tego TERYT.")
            return

        self.dockwidget.resultsTable.setRowCount(0)

        for row_html in rows[1:]:
            cols = re.findall(r"<td.*?>(.*?)</td>", row_html, re.S | re.I)
            if len(cols) < 2:
                continue
            nazwa = re.sub(r"<.*?>", "", cols[0]).strip()
            organ = re.sub(r"<.*?>", "", cols[1]).strip()
            rodzaj = re.sub(r"<.*?>", "", cols[2]).strip()
            teryt = re.sub(r"<.*?>", "", cols[3]).strip()
            wms_match = re.search(r'(https?://[^\s"\'<>]+?service=WMS[^\s"\'<>]*)', row_html, re.I)
            wfs_match = re.search(r'(https?://[^\s"\'<>]+?service=WFS[^\s"\'<>]*)', row_html, re.I)
            inspect_match = re.search(r'(index.php[^\s"\'<>]+?edycja[^\s"\'<>]*)', row_html, re.I)
            wms_url = wms_match.group(1) if wms_match else ""
            wfs_url = wfs_match.group(1) if wfs_match else ""
            inspect = inspect_match.group(1) if inspect_match else ""

            row = self.dockwidget.resultsTable.rowCount()
            self.dockwidget.resultsTable.insertRow(row)
            self.dockwidget.resultsTable.setItem(row, 0, QtWidgets.QTableWidgetItem(nazwa))
            self.dockwidget.resultsTable.setItem(row, 1, QtWidgets.QTableWidgetItem(organ))
            self.dockwidget.resultsTable.setItem(row, 2, QtWidgets.QTableWidgetItem(rodzaj))
            self.dockwidget.resultsTable.setItem(row, 3, QtWidgets.QTableWidgetItem(teryt))
            btn_wms = QtWidgets.QPushButton("+")
            btn_wfs = QtWidgets.QPushButton("+")
            btn_preview = QtWidgets.QPushButton("🌐")
            btn_inspect = QtWidgets.QPushButton("📃")
            if wms_url:
                btn_wms.clicked.connect(lambda _, u=wms_url: add_layers_from_service(u, self.iface))
                btn_preview.clicked.connect(lambda _, t=teryt, u=wms_url: self.open_geoportal_preview(t, u))
            else:
                btn_wms.setEnabled(False)
                btn_preview.setEnabled(False)
            if wfs_url:
                btn_wfs.clicked.connect(lambda _, u=wfs_url: add_layers_from_service(u, self.iface))
            else:
                btn_wfs.setEnabled(False)
            if inspect:
                inspect_url = f"https://integracja.gugik.gov.pl/eziudp/{inspect}"
                btn_inspect.clicked.connect(lambda _, i=inspect_url: QDesktopServices.openUrl(QUrl(i)))
            else:
                btn_inspect.setEnabled(False) 

            self.dockwidget.resultsTable.setCellWidget(row, 4, btn_wms)
            self.dockwidget.resultsTable.setCellWidget(row, 5, btn_wfs)
            self.dockwidget.resultsTable.setCellWidget(row, 6, btn_preview)
            self.dockwidget.resultsTable.setCellWidget(row, 7, btn_inspect)

    def open_geoportal_preview(self, teryt, wms_url):
        """Otwiera podgląd WMS w Geoportalu z bbox jednostki."""
        if not self.layer_teryt or not teryt:
            QtWidgets.QMessageBox.warning(None, "Brak danych", "Brak warstwy TERYT lub numeru.")
            return

        # Skróć TERYT w zależności od typu jednostki
        if len(teryt) >= 6:
            filter_prefix = teryt[:6]
        elif len(teryt) == 4:
            filter_prefix = teryt[:4]
        else:
            filter_prefix = teryt[:2]


        bbox = None
        for f in self.layer_teryt.getFeatures():
            val = str(f["TERYT"])
            if val.startswith(filter_prefix):
                geom = f.geometry()
                rect = geom.boundingBox()
                bbox = (rect.xMinimum(), rect.yMinimum(), rect.xMaximum(), rect.yMaximum())
                break

        
        if not bbox:
            # QtWidgets.QMessageBox.information(None, "Brak danych", f"Nie znaleziono zasięgu dla TERYT {teryt}")
            url = f"https://mapy.geoportal.gov.pl/imap/Imgp_2.html?SRS=2180&resources=map:wms@{wms_url}"
            QDesktopServices.openUrl(QUrl(url))
            return

        bbox_str = ",".join([f"{c:.2f}" for c in bbox])
        url = f"https://mapy.geoportal.gov.pl/imap/Imgp_2.html?SRS=2180&resources=map:wms@{wms_url}&bbox={bbox_str}"

        QDesktopServices.openUrl(QUrl(url))

    # ===============================
    # URUCHOMIENIE PLUGINU
    # ===============================
    def run(self):
        if not self.pluginIsActive:
            self.pluginIsActive = True
            if self.dockwidget is None:
                self.dockwidget = EziudpPlugin2Dockwidget()
            self.dockwidget.searchButton.clicked.connect(self.search_eziudp)
            self.dockwidget.pointButton.clicked.connect(self.activate_point_tool)
            self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
